### PR TITLE
tests: set owner of staging dir to jenkins user

### LINKED ISSUE #1048: staging dir owned by root:root
ceph-container nightly Jenkins jobs are failing on static slaves because the staging dir gets created and is owned (recursively) by root:root.  The jobs fail immediately when they try to wipe out the workspace.

I'm wondering if the staging dir needs to be owned by root.  If not, I will try to find a way to use sudo to clean it up.

E.g., https://2.jenkins.ceph.com/job/ceph-container-nightly-ceph_ansible-luminous-xenial-bluestore_osds_container/178/console

### PR DESCRIPTION
**Pull request by djgalloway**
Description of your changes: Sets owner of `$CEPH_ANSIBLE_SCENARIO_PATH/staging` to jenkins user so the slaves can wipe the workspace before each job.

Which issue is resolved by this Pull Request:
Resolves #1048 

Checklist:
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

File: tests/teardown.sh [hunk 1]
```diff
@@ -4,4 +4,6 @@
 . "$WORKSPACE/.tox_vars"
 cd "$CEPH_ANSIBLE_SCENARIO_PATH" || exit 1
 vagrant destroy --force
+# see https://github.com/ceph/ceph-container/issues/1048
+sudo chown -R "$(whoami)" ./staging || true
```
Comment (leseb) [inline tests/teardown.sh]: why `|| true`?

Comment (ErwanAliasr1) [reply tests/teardown.sh]: @GregMeno If you ping me on a bug I'd love having the time to wakeup and comment before you actually merge without any feedback.

The teardown is about cleaning and the makefile have some cleaning routines. So a sudo make clean should be enough.
